apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  annotations:
    appstudio.openshift.io/application: jvm-build-suite-application-pcos
    appstudio.openshift.io/component: jvm-build-suite-component-tvxw
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: jvm-build-suite-component-tvxw
  namespace: jvm-build-xypw
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-push
    template:
      ref: jvm-build-suite-component-tvxw
status:
  configuration:
    generatedName: ""
